curl 'https://lkv1fgxnwa.execute-api.eu-central-1.amazonaws.com/production/detect' \
  -H 'authority: lkv1fgxnwa.execute-api.eu-central-1.amazonaws.com' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://app.crossplag.com' \
  -H 'pragma: no-cache' \
  -H 'referer: https://app.crossplag.com/' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  --data-raw $'{"text":"AI Content Detector (Updated version)\\nUse our AI Content Detector for free to check if the text is AI-generated - now with higher accuracy\u0021\\n\\nAI Content Detector (Updated version)\\nUse our AI Content Detector for free to check if the text is AI-generated - now with higher accuracy\u0021\\n\\nAI Content Detector (Updated version)\\nUse our AI Content Detector for free to check if the text is AI-generated - now with higher accuracy\u0021\\n\\nAI Content Detector (Updated version)\\nUse our AI Content Detector for free to check if the text is AI-generated - now with higher accuracy\u0021\\n\\nAI Content Detector (Updated version)\\nUse our AI Content Detector for free to check if the text is AI-generated - now with higher accuracy\u0021"}' \
  --compressed